# Generated by Django 4.2.27 on 2026-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_assetbatch_batch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetrequest",
            name="needed_by",
            field=models.DateField(blank=True, null=True),
        ),
    ]
