# Generated by Django 4.2.27 on 2026-04-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_assetrequest_needed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetrequest",
            name="asset_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
