# Generated by Django 4.2.27 on 2026-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_assetrequest_asset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetrequest",
            name="request_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
