# Generated by Django 4.2.27 on 2026-01-19 09:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off'), ('work_from_home', 'Work From Home')], default='absent', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Total working hours', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_departure', models.BooleanField(default=False)),
                ('late_by_minutes', models.PositiveIntegerField(default=0)),
                ('early_departure_minutes', models.PositiveIntegerField(default=0)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_device', models.CharField(blank=True, max_length=100)),
                ('check_out_device', models.CharField(blank=True, max_length=100)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_regularized', models.BooleanField(default=False)),
                ('regularization_reason', models.TextField(blank=True)),
                ('regularized_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_auto_marked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.employee')),
                ('regularized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularized_attendances', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('general', 'General Shift'), ('rotational', 'Rotational')], default='general', max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_duration_minutes', models.PositiveIntegerField(default=60)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('buffer_before_minutes', models.PositiveIntegerField(default=30, help_text='How early employees can check in')),
                ('buffer_after_minutes', models.PositiveIntegerField(default=30, help_text='How late employees can check out')),
                ('working_days', models.JSONField(default=list, help_text='List of working days: [0-6] where 0=Monday, 6=Sunday')),
                ('is_active', models.BooleanField(default=True)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.organization')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('holiday_type', models.CharField(choices=[('public', 'Public Holiday'), ('restricted', 'Restricted Holiday'), ('optional', 'Optional Holiday')], default='public', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company')),
                ('departments', models.ManyToManyField(blank=True, help_text='Leave blank for company-wide holiday', related_name='holidays', to='accounts.department')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='accounts.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='attendance.shift')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('half_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('holidays', models.PositiveIntegerField(default=0)),
                ('week_offs', models.PositiveIntegerField(default=0)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('late_arrivals', models.PositiveIntegerField(default=0)),
                ('early_departures', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_finalized', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegularizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('missed_checkin', 'Missed Check-in'), ('missed_checkout', 'Missed Check-out'), ('late_arrival', 'Late Arrival'), ('early_departure', 'Early Departure'), ('full_day', 'Full Day Regularization')], max_length=50)),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='attendance/regularization/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_regularizations', to='accounts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('company', 'Company Wide'), ('department', 'Department Specific')], default='company', max_length=20)),
                ('working_days', models.CharField(choices=[('5_days', '5 Days (Mon-Fri)'), ('6_days', '6 Days (Mon-Sat)'), ('custom', 'Custom')], default='5_days', max_length=20)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('lunch_break_start', models.TimeField(default=datetime.time(13, 0))),
                ('lunch_break_end', models.TimeField(default=datetime.time(14, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum hours for half day', max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum hours for full day', max_digits=4)),
                ('overtime_applicable', models.BooleanField(default=True)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for overtime pay (e.g., 1.5 for time-and-a-half)', max_digits=4)),
                ('max_late_arrivals_per_month', models.PositiveIntegerField(default=3)),
                ('late_arrival_penalty_minutes', models.PositiveIntegerField(default=0, help_text='Deduction in minutes per late arrival')),
                ('auto_mark_absent', models.BooleanField(default=True, help_text='Automatically mark as absent if no check-in')),
                ('require_checkout', models.BooleanField(default=True)),
                ('allow_mobile_checkin', models.BooleanField(default=True)),
                ('enable_geo_fencing', models.BooleanField(default=False)),
                ('office_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_fence_radius_meters', models.PositiveIntegerField(default=100, help_text='Radius in meters for geo-fencing')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='accounts.company')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank for company-wide policy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='accounts.department')),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('tea', 'Tea Break'), ('personal', 'Personal Break'), ('other', 'Other')], default='lunch', max_length=20)),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance')),
            ],
            options={
                'ordering': ['break_start'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'is_active'], name='attendance__company_38420e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['company', 'date'], name='attendance__company_7b4347_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_active'], name='attendance__date_3ffd05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('company', 'date', 'name')},
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['employee', 'is_active'], name='attendance__employe_6fa893_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['shift', 'is_active'], name='attendance__shift_i_101c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['effective_from', 'effective_to'], name='attendance__effecti_0b0c44_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['employee', 'year', 'month'], name='attendance__employe_e6032d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('employee', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_a97fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['status', 'created_at'], name='attendance__status_379da9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepolicy',
            index=models.Index(fields=['company', 'is_active'], name='attendance__company_10aa14_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepolicy',
            index=models.Index(fields=['department', 'is_active'], name='attendance__departm_8fe422_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_9220e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
