# Generated by Django 6.0.1 on 2026-01-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=10)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Break duration in minutes"
                    ),
                ),
                (
                    "grace_period",
                    models.PositiveIntegerField(
                        default=15, help_text="Late grace period in minutes"
                    ),
                ),
                (
                    "half_day_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="Hours for half day",
                        max_digits=4,
                    ),
                ),
                (
                    "full_day_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Hours for full day",
                        max_digits=4,
                    ),
                ),
                ("is_night_shift", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("is_optional", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("company", "date")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("week_off", "Week Off"),
                            ("holiday", "Holiday"),
                            ("on_leave", "On Leave"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hours worked",
                        max_digits=5,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("is_early_leave", models.BooleanField(default=False)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_leave_minutes", models.PositiveIntegerField(default=0)),
                ("remarks", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="manual/biometric/api",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="accounts.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.shift",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Attendances",
                "ordering": ["-date", "employee"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
