# Generated by Django 4.2.27 on 2026-01-19 07:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_type', models.CharField(choices=[('lunch', 'Lunch Break'), ('tea', 'Tea Break'), ('personal', 'Personal Break'), ('other', 'Other')], default='lunch', max_length=20)),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['break_start'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('company', 'Company Wide'), ('department', 'Department Specific')], default='company', max_length=20)),
                ('working_days', models.CharField(choices=[('5_days', '5 Days (Mon-Fri)'), ('6_days', '6 Days (Mon-Sat)'), ('custom', 'Custom')], default='5_days', max_length=20)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0))),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('lunch_break_start', models.TimeField(default=datetime.time(13, 0))),
                ('lunch_break_end', models.TimeField(default=datetime.time(14, 0))),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum hours for half day', max_digits=4)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum hours for full day', max_digits=4)),
                ('overtime_applicable', models.BooleanField(default=True)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for overtime pay (e.g., 1.5 for time-and-a-half)', max_digits=4)),
                ('max_late_arrivals_per_month', models.PositiveIntegerField(default=3)),
                ('late_arrival_penalty_minutes', models.PositiveIntegerField(default=0, help_text='Deduction in minutes per late arrival')),
                ('auto_mark_absent', models.BooleanField(default=True, help_text='Automatically mark as absent if no check-in')),
                ('require_checkout', models.BooleanField(default=True)),
                ('allow_mobile_checkin', models.BooleanField(default=True)),
                ('enable_geo_fencing', models.BooleanField(default=False)),
                ('office_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('office_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_fence_radius_meters', models.PositiveIntegerField(default=100, help_text='Radius in meters for geo-fencing')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Policies',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegularizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('missed_checkin', 'Missed Check-in'), ('missed_checkout', 'Missed Check-out'), ('late_arrival', 'Late Arrival'), ('early_departure', 'Early Departure'), ('full_day', 'Full Day Regularization')], max_length=50)),
                ('requested_check_in', models.DateTimeField(blank=True, null=True)),
                ('requested_check_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='attendance/regularization/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('half_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('holidays', models.PositiveIntegerField(default=0)),
                ('week_offs', models.PositiveIntegerField(default=0)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('late_arrivals', models.PositiveIntegerField(default=0)),
                ('early_departures', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_finalized', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance Summaries',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in',
            new_name='check_in_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='check_out',
            new_name='check_out_time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='early_leave_minutes',
            new_name='early_departure_minutes',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='is_early_leave',
            new_name='is_early_departure',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='late_minutes',
            new_name='late_by_minutes',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='source',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='work_hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='break_duration',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='full_day_hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='half_day_hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_night_shift',
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_auto_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_regularized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularization_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regularized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularized_attendances', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total working hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='holiday',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for company-wide holiday', related_name='holidays', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('public', 'Public Holiday'), ('restricted', 'Restricted Holiday'), ('optional', 'Optional Holiday')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='shift',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=30, help_text='How late employees can check out'),
        ),
        migrations.AddField(
            model_name='shift',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=30, help_text='How early employees can check in'),
        ),
        migrations.AddField(
            model_name='shift',
            name='color_code',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('general', 'General Shift'), ('rotational', 'Rotational')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='working_days',
            field=models.JSONField(default=list, help_text='List of working days: [0-6] where 0=Monday, 6=Sunday'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off'), ('work_from_home', 'Work From Home')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('company', 'date', 'name')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_08d913_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_3889e6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_9220e1_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['company', 'date'], name='attendance__company_7b4347_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_active'], name='attendance__date_3ffd05_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'is_active'], name='attendance__company_38420e_idx'),
        ),
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='employeeshiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendanceregularizationrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_regularizations', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Leave blank for company-wide policy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_optional',
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['employee', 'is_active'], name='attendance__employe_6fa893_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['shift', 'is_active'], name='attendance__shift_i_101c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftassignment',
            index=models.Index(fields=['effective_from', 'effective_to'], name='attendance__effecti_0b0c44_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['employee', 'year', 'month'], name='attendance__employe_e6032d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('employee', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['employee', 'status'], name='attendance__employe_a97fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregularizationrequest',
            index=models.Index(fields=['status', 'created_at'], name='attendance__status_379da9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepolicy',
            index=models.Index(fields=['company', 'is_active'], name='attendance__company_10aa14_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepolicy',
            index=models.Index(fields=['department', 'is_active'], name='attendance__departm_8fe422_idx'),
        ),
    ]
