# Generated by Django 4.2.27 on 2026-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="holiday_type",
            field=models.CharField(
                choices=[
                    ("public", "Public Holiday"),
                    ("restricted", "Restricted Holiday"),
                    ("optional", "Optional Holiday"),
                    ("working", "Working Day"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
