# Generated by Django 4.2.27 on 2026-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_holiday_recurring_alter_holiday_holiday_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="early_departure_grace_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Grace period for early departure"
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="shift",
            name="buffer_after_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="How late employees can check out (Late Going)"
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="buffer_before_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="How early employees can check in (Early Come)"
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="grace_period_minutes",
            field=models.PositiveIntegerField(
                default=15, help_text="Grace period for late arrival"
            ),
        ),
    ]
