# Generated by Django 4.2.27 on 2026-01-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_shift_early_departure_grace_minutes_shift_is_default_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_flexible_hours",
            field=models.BooleanField(
                default=False, help_text="Employees can adjust timing"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="enable_shift_system",
            field=models.BooleanField(
                default=True, help_text="Allow multiple work shifts"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="track_break_time",
            field=models.BooleanField(default=True, help_text="Record break duration"),
        ),
    ]
