# Generated by Django 4.2.27 on 2026-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancepolicy_allow_flexible_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_after_minutes",
            field=models.PositiveIntegerField(
                default=480, help_text="Minutes after which overtime counts"
            ),
        ),
    ]
