# Generated by Django 4.2.27 on 2026-02-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancepolicy_overtime_after_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="holiday_overtime_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=2.5,
                help_text="Multiplier for holiday overtime pay",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_overtime_per_day",
            field=models.PositiveIntegerField(
                default=4, help_text="Maximum overtime hours allowed per day"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_overtime_per_week",
            field=models.PositiveIntegerField(
                default=20, help_text="Maximum overtime hours allowed per week"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="min_overtime_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="Minimum overtime minutes to qualify for pay"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="require_overtime_pre_approval",
            field=models.BooleanField(
                default=False,
                help_text="Require manager approval before working overtime",
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="weekend_overtime_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=2.0,
                help_text="Multiplier for weekend overtime pay",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="attendancepolicy",
            name="overtime_rate_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Multiplier for regular overtime pay (e.g., 1.5 for time-and-a-half)",
                max_digits=4,
            ),
        ),
    ]
