# Generated by Django 4.2.27 on 2026-03-28 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendancepolicy_holiday_overtime_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="allowed_ips",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of allowed IP addresses"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="auto_clockout_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="auto_clockout_time",
            field=models.TimeField(blank=True, default=datetime.time(22, 0), null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="early_thresholds",
            field=models.JSONField(
                default=list, help_text="JSON list of early going penalty rules"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="ip_restriction_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="late_thresholds",
            field=models.JSONField(
                default=list, help_text="JSON list of late penalty rules"
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_regularization_attempts_per_month",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
