# Generated by Django 4.2.27 on 2026-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_attendancepolicy_allowed_ips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_checkin_correction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_checkout_correction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_missed_attendance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="auto_approve_after_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="enable_attendance_requests",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_requests_per_month",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="request_deadline_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="require_proof",
            field=models.BooleanField(default=False),
        ),
    ]
