# Generated by Django 4.2.27 on 2026-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_attendancepolicy_allow_checkin_correction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="regularization_proof",
            field=models.FileField(
                blank=True, null=True, upload_to="attendance/regularization/"
            ),
        ),
    ]
