# Generated by Django 4.2.27 on 2026-04-03 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employee_onboarding_status_and_more'),
        ('attendance', '0009_attendance_regularization_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('hours_requested', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='accounts.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_overtimes', to='accounts.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'status'], name='attendance__employe_c62e32_idx'), models.Index(fields=['date', 'status'], name='attendance__date_ef46da_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
