# Generated by Django 4.2.27 on 2026-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_regularization_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('holiday', 'Holiday'), ('week_off', 'Week Off'), ('work_from_home', 'Work From Home'), ('late', 'Late')], default='absent', max_length=20),
        ),
    ]
