# Generated by Django 4.2.27 on 2026-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_attendance_status"),
        ("attendance", "0010_overtimerequest"),
    ]

    operations = []
