# Generated by Django 4.2.27 on 2026-03-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseclaim",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="expenses.expensecategory",
            ),
        ),
        migrations.AlterField(
            model_name="expenseclaim",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="expenses/claims/"),
        ),
    ]
