# Generated by Django 4.2.27 on 2026-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expenseclaim_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaim",
            name="approval_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="current_stage",
            field=models.CharField(
                choices=[
                    ("level1", "Manager Approval"),
                    ("level2", "Finance Approval"),
                    ("completed", "Completed"),
                ],
                default="level1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expenseclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
