# Generated by Django 4.2.27 on 2026-01-31 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_role", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("UPLOAD", "Upload"),
                            ("PROCESS", "Process"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=50)),
                (
                    "reference_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("description", models.TextField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="SUCCESS", max_length=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="audit_syste_timesta_5ffd22_idx"
                    )
                ],
            },
        ),
    ]
