# Generated by Django 4.2.27 on 2026-01-31 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("user_role", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("UPLOAD", "Upload"),
                            ("PROCESS", "Process"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("AUTH", "Authentication"),
                            ("EMPLOYEE", "Employee Management"),
                            ("SALARY", "Salary Management"),
                            ("ATTENDANCE", "Attendance"),
                            ("PAYROLL", "Payroll"),
                            ("BULK_UPLOAD", "Bulk Upload"),
                            ("SUPPORT", "Support"),
                            ("SYSTEM", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("description", models.TextField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        db_index=True,
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.DeleteModel(
            name="SystemLog",
        ),
    ]
