# Generated by Django 4.2.27 on 2026-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_activitylog_delete_systemlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="module",
            field=models.CharField(
                choices=[
                    ("AUTH", "Authentication"),
                    ("EMPLOYEE", "Employee Management"),
                    ("SALARY", "Salary Management"),
                    ("ATTENDANCE", "Attendance"),
                    ("PAYROLL", "Payroll"),
                    ("BULK_UPLOAD", "Bulk Upload"),
                    ("SUPPORT", "Support"),
                    ("SYSTEM", "System"),
                    ("LEAVE", "Leave Management"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
