# Generated by Django 4.2.27 on 2026-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarycomponent",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Amount"),
                    ("percentage", "Percentage of Basic"),
                    ("formula", "Custom Formula"),
                    ("attendance_prorated", "Attendance Prorated"),
                    ("per_day", "Per Present Day"),
                ],
                default="fixed",
                max_length=20,
            ),
        ),
    ]
