# Generated by Django 4.2.27 on 2026-02-04 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_20260204_1243"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSlab",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[("new", "New Regime"), ("old", "Old Regime")],
                        max_length=10,
                    ),
                ),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage", max_digits=5
                    ),
                ),
                (
                    "cess",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Health and Education Cess %",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_slabs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tax Slabs",
                "ordering": ["regime", "min_income"],
            },
        ),
        migrations.CreateModel(
            name="TaxDeclaration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g., 2025-2026", max_length=9),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[("new", "New Regime"), ("old", "Old Regime")],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("declarations", models.JSONField(default=list)),
                (
                    "total_declared_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_declarations",
                        to="accounts.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_declarations",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("employee", "financial_year")},
            },
        ),
    ]
