# Generated by Django 4.2.27 on 2026-02-06 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_20260204_1243"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0002_taxslab_taxdeclaration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enable_auto_tds",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic TDS calculation during payroll",
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(
                        default="2025-2026",
                        help_text="Current financial year (e.g., 2025-2026)",
                        max_length=9,
                    ),
                ),
                (
                    "default_tax_regime",
                    models.CharField(
                        choices=[("new", "New Regime"), ("old", "Old Regime")],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "allow_manual_tds_override",
                    models.BooleanField(
                        default=False,
                        help_text="Allow admin to manually override TDS amounts",
                    ),
                ),
                (
                    "apply_tds_monthly",
                    models.BooleanField(
                        default=True, help_text="Standard monthly TDS deduction"
                    ),
                ),
                ("pf_enabled", models.BooleanField(default=True)),
                ("esi_enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_settings",
                        to="accounts.organization",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payroll Settings",
            },
        ),
    ]
