# Generated by Django 4.2.27 on 2026-02-06 09:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_payrollsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="esi_contribution_rate_employee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.75"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="esi_contribution_rate_employer",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("3.25"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="esi_wage_ceiling",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("21000.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_contribution_rate_employee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("12.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_contribution_rate_employer",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("12.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_include_employer_share_in_ctc",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_is_restricted_basic",
            field=models.BooleanField(
                default=True,
                help_text="Restrict PF calculation to ceiling if basic > ceiling",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_wage_ceiling",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("15000.00"), max_digits=12
            ),
        ),
    ]
