# Generated by Django 4.2.27 on 2026-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_loan_emi"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslipcomponent",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
    ]
