# Generated by Django 4.2.27 on 2026-02-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_payslipcomponent_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollperiod",
            name="total_advance_recovery",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_lop",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="payrollperiod",
            name="total_statutory",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="payslip",
            name="advance_recovery",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="statutory_deductions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
