# Generated by Django 4.2.27 on 2026-02-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_adhocpayment"),
        ("payroll", "0007_payrollperiod_total_advance_recovery_and_more"),
    ]

    operations = []
