# Generated by Django 4.2.27 on 2026-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_merge_20260209_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="default_from_email",
            field=models.CharField(
                blank=True, help_text="From Email Address", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="email_host",
            field=models.CharField(
                blank=True, help_text="SMTP Host (e.g., smtp.gmail.com)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="email_host_password",
            field=models.CharField(
                blank=True, help_text="Email Password / App Password", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="email_host_user",
            field=models.CharField(
                blank=True, help_text="Email Address", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="email_port",
            field=models.PositiveIntegerField(
                default=587, help_text="SMTP Port (e.g., 587)"
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="email_use_tls",
            field=models.BooleanField(default=True, help_text="Use TLS"),
        ),
    ]
