# Generated by Django 4.2.27 on 2026-03-25 09:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_salesrecord_commissionrule_commissionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_admin_charges_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.50"),
                help_text="PF Admin Charges %",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_contribution_rate_epf_employer",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("3.67"),
                help_text="EPF rate (Employer share)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_contribution_rate_eps",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.33"),
                help_text="Pension Fund rate (Employer share)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="pf_edli_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.50"),
                help_text="EDLI Charges %",
                max_digits=5,
            ),
        ),
    ]
