# Generated by Django 6.0.3 on 2026-03-14 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_employee_esi_number_employee_uan_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=120)),
                ('field_key', models.SlugField(max_length=140)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_custom_fields', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active'], name='hrms_employ_company_4ec3f3_idx'), models.Index(fields=['company', 'field_type'], name='hrms_employ_company_7f9cc0_idx')],
                'unique_together': {('company', 'field_key')},
            },
        ),
    ]
