# Generated by Django 6.0.3 on 2026-03-14 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_employee_esi_number_employee_uan_number'),
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_document_types', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_active'], name='hrms_employ_company_0a05fe_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
