# Generated by Django 6.0.3 on 2026-03-14 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_employee_esi_number_employee_uan_number'),
        ('hrms', '0002_employeedocumenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_templates', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=200)),
                ('step_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hrms.onboardingtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['company', 'is_active'], name='hrms_onboar_company_a6911f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtemplate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='onboardingstep',
            index=models.Index(fields=['template', 'step_order'], name='hrms_onboar_templat_796625_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='onboardingstep',
            unique_together={('template', 'step_order')},
        ),
    ]
