# Generated by Django 4.2.27 on 2026-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0003_onboardingtemplate_onboardingstep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecustomfield",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional hint or instruction for the employee.",
                null=True,
            ),
        ),
    ]
