# Generated by Django 4.2.27 on 2026-03-28 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0018_employee_onboarding_status_and_more"),
        ("hrms", "0004_employeecustomfield_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeOnboardingStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_steps",
                        to="accounts.employee",
                    ),
                ),
                (
                    "template_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hrms.onboardingstep",
                    ),
                ),
            ],
            options={
                "ordering": ["template_step__step_order", "created_at"],
                "unique_together": {("employee", "template_step")},
            },
        ),
    ]
