# Generated by Django 4.2.27 on 2026-01-19 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('free_trial', 'Free Trial'), ('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('enterprise', 'Enterprise')], db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quarterly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quarterly_discount_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('max_employees', models.PositiveIntegerField(blank=True, help_text='Maximum employees allowed. Null = unlimited', null=True)),
                ('max_companies', models.PositiveIntegerField(default=1, help_text='Maximum companies/subsidiaries allowed')),
                ('max_departments', models.PositiveIntegerField(blank=True, null=True)),
                ('max_storage_gb', models.PositiveIntegerField(default=5)),
                ('features', models.JSONField(default=dict, help_text="Package features as JSON: {'payroll': true, 'attendance': true}")),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tag_line', models.CharField(blank=True, max_length=100)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('past_due', 'Past Due')], db_index=True, default='trial', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('company_count', models.PositiveIntegerField(default=1)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_renew', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gateway', models.CharField(help_text='stripe, razorpay, etc.', max_length=50)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_url', models.URLField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100)),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('usage_date', models.DateField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='subscriptions.subscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='subscriptio_organiz_3cb096_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_e7d593_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'auto_renew'], name='subscriptio_status_afe6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'status'], name='subscriptio_subscri_0bac84_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='subscriptio_transac_572a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'gateway_payment_id'], name='subscriptio_gateway_b6340e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice_number'], name='subscriptio_invoice_f03a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type', 'is_active'], name='subscriptio_package_ba0d99_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['subscription', 'usage_date'], name='subscriptio_subscri_c2e861_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['feature_name', 'usage_date'], name='subscriptio_feature_8ecc7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featureusage',
            unique_together={('subscription', 'feature_name', 'usage_date')},
        ),
    ]
