# Generated by Django 4.2.27 on 2026-01-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequest",
            name="direction",
            field=models.CharField(
                choices=[
                    ("admin_to_employee", "Admin Requesting from Employee"),
                    ("employee_to_admin", "Employee Requesting from Admin"),
                ],
                default="employee_to_admin",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="document_requests/"
            ),
        ),
        migrations.AddField(
            model_name="documentrequest",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
