# Generated by Django 4.2.27 on 2026-01-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("self", "Self Only"),
                            ("team", "Team/Subordinates"),
                            ("department", "Department"),
                            ("branch", "Branch/Location"),
                            ("company", "Company"),
                            ("organization", "Organization (All Companies)"),
                            ("global", "Global/All"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Hierarchy level: 1=Self, 2=Team, 3=Department, etc."
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("core", "Core Management"),
                            ("employee", "Employee Management"),
                            ("attendance", "Attendance & Time Tracking"),
                            ("leave", "Leave Management"),
                            ("shift", "Shift Management"),
                            ("payroll", "Payroll"),
                            ("recruitment", "Recruitment"),
                            ("performance", "Performance Management"),
                            ("training", "Training & Development"),
                            ("assets", "Asset Management"),
                            ("documents", "Document Management"),
                            ("reports", "Reports & Analytics"),
                            ("settings", "System Settings"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class name", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View/Read"),
                            ("create", "Create"),
                            ("edit", "Edit/Update"),
                            ("delete", "Delete"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("process", "Process"),
                            ("manage", "Full Management"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.module",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "action", "name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[("system", "System Role"), ("custom", "Custom Role")],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="accounts.datascope",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-wide roles",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional conditions: {'status': 'active', 'employment_type': 'permanent'}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.role"
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="Data access scope for this permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.datascope",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="accounts.RolePermission",
                to="accounts.permission",
            ),
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("check", "Permission Check"),
                            ("grant", "Permission Granted"),
                            ("revoke", "Permission Revoked"),
                            ("role_assign", "Role Assigned"),
                            ("role_remove", "Role Removed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.BooleanField(help_text="True if allowed, False if denied"),
                ),
                ("scope_used", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Role applies to this department only",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_assignments",
                        to="accounts.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_role_assignments",
                        to="accounts.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="accounts.role",
                    ),
                ),
                (
                    "scope_override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override default role scope for this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.datascope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_us_user_id_2517ab_idx",
                    ),
                    models.Index(
                        fields=["role", "is_active"],
                        name="accounts_us_role_id_327ba4_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="accounts_us_organiz_70f4c8_idx",
                    ),
                ],
                "unique_together": {("user", "role", "organization", "department")},
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grant_type",
                    models.CharField(
                        choices=[("grant", "Grant"), ("revoke", "Revoke")],
                        default="grant",
                        help_text="Grant gives permission, Revoke removes it even if role has it",
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this direct permission?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permission",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.datascope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_us_user_id_ba4aae_idx",
                    ),
                    models.Index(
                        fields=["permission", "grant_type"],
                        name="accounts_us_permiss_105bb7_idx",
                    ),
                ],
                "unique_together": {("user", "permission", "organization")},
            },
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["role", "permission"], name="accounts_ro_role_id_5b564a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["organization", "is_active"],
                name="accounts_ro_organiz_46fa3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="accounts_ro_code_5aeee6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["user", "created_at"], name="accounts_pe_user_id_4b7885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["permission", "result"], name="accounts_pe_permiss_a0ff45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permissionauditlog",
            index=models.Index(
                fields=["action", "created_at"], name="accounts_pe_action_4aca65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(
                fields=["module", "is_active"], name="accounts_pe_module__808493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="accounts_pe_code_3a265a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("module", "code")},
        ),
    ]
