# Generated by Django 4.2.27 on 2026-01-19 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignationPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional conditions for this permission",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.designation",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.permission",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        help_text="Data access scope for this permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.datascope",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="designation",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions directly assigned to this designation",
                related_name="designations",
                through="accounts.DesignationPermission",
                to="accounts.permission",
            ),
        ),
        migrations.AddIndex(
            model_name="designationpermission",
            index=models.Index(
                fields=["designation", "permission"],
                name="accounts_de_designa_350d90_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="designationpermission",
            unique_together={("designation", "permission")},
        ),
    ]
