# Generated by Django 4.2.27 on 2026-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_datascope_module_permission_role_rolepermission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles automatically granted to employees with this designation",
                related_name="designations",
                to="accounts.role",
            ),
        ),
    ]
