# Generated by Django 4.2.27 on 2026-01-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_designation_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has administrative access",
            ),
        ),
    ]
