# Generated by Django 4.2.27 on 2026-02-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_datascope_created_at_datascope_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="biometric_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID as registered in Biometric Device",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
