# Generated by Django 4.2.27 on 2026-02-02 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_datascope_created_at_datascope_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pin_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("is_pin_enabled", models.BooleanField(default=False)),
                (
                    "clearance_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Level 1 - Basic"),
                            (2, "Level 2 - Standard"),
                            (3, "Level 3 - High"),
                            (4, "Level 4 - Critical"),
                        ],
                        default=1,
                    ),
                ),
                ("last_pin_change", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Profile",
                "verbose_name_plural": "Security Profiles",
            },
        ),
    ]
