# Generated by Django 4.2.27 on 2026-02-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_employee_biometric_id"),
        ("accounts", "0006_securityprofile"),
    ]

    operations = []
