# Generated by Django 4.2.27 on 2026-02-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_merge_0006_employee_biometric_id_0006_securityprofile"),
        ("accounts", "0009_add_tax_management_setting"),
    ]

    operations = []
