# Generated by Django 4.2.27 on 2026-02-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_20260204_1243"),
        ("accounts", "0010_merge_20260204_1243"),
    ]

    operations = []
