# Generated by Django 4.2.27 on 2026-02-07 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_merge_20260207_1124"),
        ("accounts", "0011_merge_20260207_1142"),
    ]

    operations = []
