# Generated by Django 4.2.27 on 2026-02-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_merge_20260207_1529"),
        ("accounts", "0012_merge_20260209_1058"),
    ]

    operations = []
