# Generated by Django 4.2.27 on 2026-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_merge_20260209_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="esi_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ESI Number"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="uan_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="UAN Number"
            ),
        ),
    ]
