# Generated by Django 4.2.27 on 2026-03-27 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityprofile",
            name="password_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
