# Generated by Django 4.2.27 on 2026-03-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_securityprofile_password_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
