# Generated by Django 4.2.27 on 2026-03-28 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_employeecustomfield_description"),
        ("accounts", "0017_employee_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="onboarding_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarded_employees",
                to="hrms.onboardingtemplate",
            ),
        ),
    ]
