# Generated by Django 4.2.27 on 2026-02-13 06:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applied_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("SCREENING", "Screening"),
                            ("PHONE_SCREEN", "Phone Screen"),
                            ("TECHNICAL_INTERVIEW", "Technical Interview"),
                            ("HR_INTERVIEW", "HR Interview"),
                            ("MANAGER_INTERVIEW", "Manager Interview"),
                            ("FINAL_ROUND", "Final Round"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="APPLIED",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "offer_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("offer_joining_date", models.DateField(blank=True, null=True)),
                (
                    "offer_acceptance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("NEGOTIATING", "Negotiating"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-applied_date"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("current_job_title", models.CharField(blank=True, max_length=200)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                ("total_experience_years", models.PositiveIntegerField(default=0)),
                ("total_experience_months", models.PositiveIntegerField(default=0)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                (
                    "notice_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("15_DAYS", "15 Days"),
                            ("1_MONTH", "1 Month"),
                            ("2_MONTHS", "2 Months"),
                            ("3_MONTHS", "3 Months"),
                            ("SERVING_NOTICE", "Serving Notice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("education", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("JOB_PORTAL", "Job Portal"),
                            ("LINKEDIN", "LinkedIn"),
                            ("REFERRAL", "Referral"),
                            ("CAREER_PAGE", "Career Page"),
                            ("DIRECT_APPLICATION", "Direct Application"),
                            ("SOCIAL_MEDIA", "Social Media"),
                            ("RECRUITMENT_AGENCY", "Recruitment Agency"),
                            ("CAMPUS_HIRING", "Campus Hiring"),
                            ("OTHER", "Other"),
                        ],
                        default="DIRECT_APPLICATION",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("SCREENING", "Screening"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("INTERVIEW", "Interview"),
                            ("OFFERED", "Offered"),
                            ("HIRED", "Hired"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "technical_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "culture_fit_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_blacklisted", models.BooleanField(default=False)),
                ("blacklist_reason", models.TextField(blank=True)),
                ("is_starred", models.BooleanField(default=False)),
                ("last_activity_date", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("PHONE_SCREEN", "Phone Screen"),
                            ("VIDEO", "Video"),
                            ("IN_PERSON", "In-Person"),
                            ("TECHNICAL", "Technical"),
                            ("HR", "HR"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("PANEL", "Panel"),
                            ("CASE_STUDY", "Case Study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("meeting_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RESCHEDULED", "Rescheduled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("preparation_notes", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("previous_date", models.DateTimeField(blank=True, null=True)),
                ("reschedule_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.application",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ENGINEERING", "Engineering"),
                            ("MARKETING", "Marketing"),
                            ("SALES", "Sales"),
                            ("HR", "HR"),
                            ("FINANCE", "Finance"),
                            ("OPERATIONS", "Operations"),
                            ("CUSTOMER_SUPPORT", "Customer Support"),
                            ("PRODUCT", "Product"),
                            ("DESIGN", "Design"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                            ("TEMPORARY", "Temporary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Level"),
                            ("MID", "Mid Level"),
                            ("SENIOR", "Senior Level"),
                            ("LEAD", "Lead"),
                            ("MANAGER", "Manager"),
                            ("DIRECTOR", "Director"),
                            ("EXECUTIVE", "Executive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=10)),
                ("description", models.TextField()),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("openings", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("ON_HOLD", "On Hold"),
                            ("CLOSED", "Closed"),
                            ("FILLED", "Filled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("target_start_date", models.DateField(blank=True, null=True)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("is_remote", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruiters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                (
                    "overall_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "technical_skills",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "problem_solving",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "culture_fit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=2,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_HIRE", "Strong Hire"),
                            ("HIRE", "Hire"),
                            ("MAYBE", "Maybe"),
                            ("NO_HIRE", "No Hire"),
                            ("STRONG_NO_HIRE", "Strong No Hire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitment.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                related_name="conducted_interviews",
                through="recruitment.InterviewFeedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="job_opening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="recruitment.jobopening",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="rescheduled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CandidateNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="recruitment.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.candidate",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job_opening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.jobopening",
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["status", "-posted_date"], name="recruitment_status_5cdb0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=models.Index(
                fields=["department"], name="recruitment_departm_788ca9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewfeedback",
            unique_together={("interview", "interviewer")},
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["candidate", "scheduled_date"],
                name="recruitment_candida_4024f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="recruitment_status_22a358_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["email"], name="recruitment_email_9164c0_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["status"], name="recruitment_status_5d798c_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job_opening", "status"], name="recruitment_job_ope_fbe891_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate", "-applied_date"],
                name="recruitment_candida_70fdc6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job_opening")},
        ),
    ]
