# Generated by Django 6.0.3 on 2026-03-09 07:38

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_RECRUITMENT_STAGES = [
    {"name": "Applied", "sequence": 1, "is_system": True},
    {"name": "Screening", "sequence": 2, "is_system": False},
    {"name": "Technical Interview", "sequence": 3, "is_system": False},
    {"name": "Cultural Fit Round", "sequence": 4, "is_system": False},
    {"name": "Offer", "sequence": 5, "is_system": True},
    {"name": "Hired", "sequence": 6, "is_system": True},
    {"name": "Rejected", "sequence": 7, "is_system": True},
]


def seed_recruitment_stages(apps, schema_editor):
    RecruitmentStage = apps.get_model('recruitment', 'RecruitmentStage')
    Candidate = apps.get_model('recruitment', 'Candidate')

    stage_map = {}
    for stage in DEFAULT_RECRUITMENT_STAGES:
        stage_obj, _ = RecruitmentStage.objects.update_or_create(
            name=stage["name"],
            defaults={
                "sequence": stage["sequence"],
                "is_system": stage["is_system"],
            },
        )
        stage_map[stage["name"]] = stage_obj

    status_mapping = {
        "NEW": "Applied",
        "SCREENING": "Screening",
        "SHORTLISTED": "Screening",
        "INTERVIEW": "Technical Interview",
        "OFFERED": "Offer",
        "HIRED": "Hired",
        "REJECTED": "Rejected",
    }

    default_stage = stage_map["Applied"]
    for candidate in Candidate.objects.all():
        stage_name = status_mapping.get(candidate.status, "Applied")
        candidate.stage_id = stage_map.get(stage_name, default_stage).id
        candidate.save(update_fields=["stage"])


def remove_recruitment_stages(apps, schema_editor):
    RecruitmentStage = apps.get_model('recruitment', 'RecruitmentStage')
    RecruitmentStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.IntegerField(unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruitment.recruitmentstage'),
        ),
        migrations.RunPython(seed_recruitment_stages, remove_recruitment_stages),
    ]
