# Generated by Django 6.0.3 on 2026-03-09 08:32

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_SKILL_CATEGORIES = [
    {"name": "Development", "description": "Technical and engineering skills used for software and product roles."},
    {"name": "Design", "description": "Product, visual, and interaction design skills used in creative roles."},
    {"name": "Soft Skills", "description": "Communication, leadership, and behavioral skills used across roles."},
]


def seed_skill_categories(apps, schema_editor):
    SkillCategory = apps.get_model('recruitment', 'SkillCategory')

    for category in DEFAULT_SKILL_CATEGORIES:
        SkillCategory.objects.get_or_create(
            name=category["name"],
            defaults={"description": category["description"]},
        )


def remove_skill_categories(apps, schema_editor):
    SkillCategory = apps.get_model('recruitment', 'SkillCategory')
    SkillCategory.objects.filter(name__in=[category["name"] for category in DEFAULT_SKILL_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentstage_candidate_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.skillcategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.RunPython(seed_skill_categories, remove_skill_categories),
    ]
