# Generated by Django 6.0.3 on 2026-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_skillcategory_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='experience_required',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='job_openings', to='recruitment.skill'),
        ),
    ]
