# Generated by Django 6.0.3 on 2026-03-09 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobopening_experience_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='applied_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_skills',
            field=models.ManyToManyField(blank=True, related_name='candidate_profiles', to='recruitment.skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruitment.jobopening'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidatenote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='department',
            field=models.CharField(choices=[('ENGINEERING', 'Engineering'), ('IT', 'IT'), ('MARKETING', 'Marketing'), ('SALES', 'Sales'), ('HR', 'HR'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('PRODUCT', 'Product'), ('DESIGN', 'Design'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
