# Generated by Django 6.0.3 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_applied_date_candidate_candidate_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In-Person')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='interview',
            name='location_or_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='result',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]

