# Generated by Django 6.0.3 on 2026-03-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_interview_interview_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral')], default='WEBSITE', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_in_stage', to='recruitment.recruitmentstage'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('ON_HOLD', 'On Hold')], default='APPLIED', max_length=20),
        ),
    ]
