# Generated by Django 6.0.3 on 2026-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_application_source_application_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentJobSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_job_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('default_experience', models.CharField(choices=[('FRESHER', 'Fresher'), ('ONE_TO_THREE', '1-3 Years'), ('THREE_TO_FIVE', '3-5 Years'), ('FIVE_PLUS', '5+ Years')], default='FRESHER', max_length=20)),
                ('allow_remote', models.BooleanField(default=False)),
                ('default_expiry_days', models.PositiveIntegerField(default=30)),
                ('default_vacancies', models.PositiveIntegerField(default=1)),
                ('auto_close_job', models.BooleanField(default=True)),
                ('allow_multiple_locations', models.BooleanField(default=False)),
                ('candidate_sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recruitment Job Posting Setting',
                'verbose_name_plural': 'Recruitment Job Posting Settings',
            },
        ),
    ]
