# Generated by Django 6.0.3 on 2026-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_recruitmentjobsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentstage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
