# Generated by Django 6.0.3 on 2026-03-12 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_recruitmentstage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('RATING', 'Rating (1-5)'), ('TEXT', 'Text'), ('YES_NO', 'Yes/No'), ('DROPDOWN', 'Dropdown')], default='TEXT', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recruitment.interviewtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['template', 'order'], name='recruitment_templat_da92a0_idx')],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
