# Generated by Django 4.2.27 on 2026-03-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0011_interviewtemplate_interviewquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_text", models.CharField(max_length=200, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["reason_text"],
            },
        ),
    ]
