# Generated by Django 4.2.27 on 2026-04-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="solution",
            field=models.TextField(blank=True, null=True),
        ),
    ]
