# Generated by Django 6.0.1 on 2026-01-16 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                (
                    "days_per_year",
                    models.DecimalField(decimal_places=2, default=12, max_digits=5),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        default=3, help_text="Max days allowed in one request"
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("is_carry_forward", models.BooleanField(default=False)),
                (
                    "max_carry_forward_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "is_encashable",
                    models.BooleanField(
                        default=False, help_text="Can be converted to money"
                    ),
                ),
                (
                    "applicable_after_months",
                    models.PositiveIntegerField(
                        default=0, help_text="Months after joining"
                    ),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, help_text="Requires medical certificate etc."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "start_day_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full",
                        max_length=15,
                    ),
                ),
                (
                    "end_day_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full",
                        max_length=15,
                    ),
                ),
                ("days_count", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField()),
                ("contact_during_leave", models.CharField(blank=True, max_length=15)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_documents/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="core.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="core.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pending",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Pending approval",
                        max_digits=5,
                    ),
                ),
                (
                    "carry_forward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="core.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leave.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
    ]
