# Generated by Django 4.2.27 on 2026-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_permissions_and_roles'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('company', 'name')},
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
