# Generated by Django 4.2.27 on 2026-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leavetype_unique_together_alter_leavetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='accrual_type',
            field=models.CharField(choices=[('full_year', 'Full Year (at Start)'), ('monthly', 'Monthly Accrual'), ('quarterly', 'Quarterly Accrual')], default='full_year', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='reset_cycle',
            field=models.CharField(choices=[('calendar', 'Calendar Year (Jan-Dec)'), ('fiscal', 'Fiscal Year (Apr-Mar)')], default='calendar', max_length=20),
        ),
    ]
