# Generated by Django 4.2.27 on 2026-04-01 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employee_onboarding_status_and_more'),
        ('leave', '0003_leavetype_accrual_type_leavetype_reset_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start', models.CharField(default='04-01', help_text='MM-DD format', max_length=5)),
                ('default_probation_months', models.PositiveIntegerField(default=6)),
                ('allow_negative_balance', models.BooleanField(default=False)),
                ('auto_approve_short_leave', models.BooleanField(default=False)),
                ('notify_manager_high_usage', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Global leave settings',
            },
        ),
    ]
