# Generated by Django 4.2.27 on 2026-04-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employee_onboarding_status_and_more'),
        ('leave', '0003_leavetype_accrual_type_leavetype_reset_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEncashment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('days_encashed', models.DecimalField(decimal_places=2, help_text='Number of leave days being encashed', max_digits=5)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Employee daily salary rate at time of request (gross/26)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='days_encashed × daily_rate', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_encashments', to='accounts.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_encashments', to='accounts.employee')),
                ('leave_type', models.ForeignKey(help_text='Must have is_encashable=True', on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Encashment',
                'verbose_name_plural': 'Leave Encashments',
                'ordering': ['-created_at'],
            },
        ),
    ]
