# Generated by Django 4.2.27 on 2026-04-03 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_employee_onboarding_status_and_more'),
        ('leave', '0004_add_leave_encashment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_encashment_enabled', models.BooleanField(default=True, help_text='Enable/Disable the entire Leave Encashment module')),
                ('fiscal_year_start', models.CharField(default='04-01', help_text='MM-DD format (default April 1st)', max_length=5)),
                ('default_probation_months', models.PositiveIntegerField(default=6, help_text='Standard probation period for new employees')),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='Permit advance leaves')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_settings', to='accounts.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Settings',
            },
        ),
    ]
