# Generated by Django 4.2.27 on 2026-04-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leavesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesettings',
            name='auto_approve_short_leaves',
            field=models.BooleanField(default=False, help_text='Automatically approve requests <= 1 day'),
        ),
        migrations.AddField(
            model_name='leavesettings',
            name='notify_manager_high_usage',
            field=models.BooleanField(default=True, help_text='Notify managers if leave usage exceeds 80%'),
        ),
    ]
