# Generated by Django 4.2.27 on 2026-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0004_globalleavesettings"),
        ("leave", "0006_leavesettings_auto_approve_short_leaves_and_more"),
    ]

    operations = []
