# Generated by Django 4.2.27 on 2026-04-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_employee_onboarding_status_and_more"),
        ("leave", "0007_merge_20260404_1439"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaveencashment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leavesettings",
            options={"verbose_name_plural": "Leave settings"},
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="allow_negative_balance",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="auto_approve_short_leaves",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="default_probation_months",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="fiscal_year_start",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="notify_manager_high_usage",
        ),
        migrations.RemoveField(
            model_name="leavesettings",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="leaveencashment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavesettings",
            name="max_encashable_days_per_year",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="leavesettings",
            name="min_days_for_encashment",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="leaveencashment",
            name="daily_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rate at the time of encashment",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="leaveencashment",
            name="days_encashed",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="leaveencashment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encashments",
                to="accounts.employee",
            ),
        ),
        migrations.AlterField(
            model_name="leaveencashment",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leave.leavetype"
            ),
        ),
        migrations.AlterField(
            model_name="leaveencashment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name="leavesettings",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advanced_leave_settings",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="leavesettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="leavesettings",
            name="is_encashment_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
