# Generated by Django 4.2.27 on 2026-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_alter_goal_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
