# Generated by Django 4.2.27 on 2026-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_alter_goal_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewperiod",
            name="auto_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reviewperiod",
            name="enable_manager_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reviewperiod",
            name="enable_peer_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewperiod",
            name="enable_self_assessment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reviewperiod",
            name="reminder_days",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
