# Generated by Django 4.2.27 on 2026-02-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0004_reviewperiod_auto_reminders_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancereview",
            name="goal_completion_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average goal completion percentage from objectives",
                max_digits=5,
                null=True,
            ),
        ),
    ]
