# Generated by Django 4.2.27 on 2026-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_goal_completion_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancecriteria",
            name="color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
