# Generated by Django 4.2.27 on 2026-02-02 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_employee_biometric_id"),
        ("attendance", "0005_attendancepolicy_overtime_after_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("device_model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=4370)),
                ("protocol", models.CharField(default="TCP/IP", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Main Entrance, Cafeteria",
                        max_length=200,
                    ),
                ),
                ("total_logs_fetched", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_devices",
                        to="accounts.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiometricLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("biometric_user_id", models.CharField(db_index=True, max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "verify_mode",
                    models.IntegerField(
                        default=0,
                        help_text="1: Fingerprint, 3: Password, 4: Card, 15: Face",
                    ),
                ),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_record",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_biometric_log",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="biometrics.biometricdevice",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biometric_logs",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("device", "biometric_user_id", "timestamp")},
            },
        ),
    ]
