# Generated by Django 4.2.27 on 2026-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biometrics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biometricdevice",
            name="protocol",
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="activate_live_capture",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="api_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="connection_method",
            field=models.CharField(
                choices=[
                    ("api", "API (Cloud)"),
                    ("ip", "Local Network (IP)"),
                    ("excel", "Excel Upload"),
                    ("manual", "Manual Entry"),
                ],
                default="ip",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="device_direction",
            field=models.CharField(
                choices=[
                    ("in", "In Device"),
                    ("out", "Out Device"),
                    ("both", "System Direction (In/Out)"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="biometricdevice",
            name="sync_mode",
            field=models.CharField(
                choices=[("auto", "Auto Sync"), ("manual", "Manual Sync Only")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="biometricdevice",
            name="ip_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
